name: Generate Pokemon Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate Pokemon catching contributions
        uses: Platane/snk@v3
        with:
          github_user_name: ajengazr
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#fbbf24&color_dots=#1e293b,#0f172a,#fb923c,#f97316,#ea580c
            dist/ocean.gif?color_snake=#fbbf24&color_dots=#1e293b,#0f172a,#fb923c,#f97316,#ea580c

      - name: Push Pokemon animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
